x-versions: &compiler_versions
  GCC_HEAD_VERSION: 16
  LLVM_HEAD_VERSION: 22

x-image-versions: &image_versions
  BASE_IMAGE: docker.io/library/ubuntu:jammy
  ACTIONS_BASE_IMAGE: ghcr.io/llvm/libcxx-linux-builder-base:77cb0980bcc2675b27d08141526939423fa0be76

services:
  builder-base:
    image: ghcr.io/llvm/libcxx-linux-builder-base:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-base
      args:
        <<: [*image_versions, *compiler_versions]

  actions-builder:
    image: ghcr.io/llvm/libcxx-linux-builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: actions-builder
      args:
        GITHUB_RUNNER_VERSION: "2.328.0"
        <<: [*image_versions, *compiler_versions]

  android-buildkite-builder:
    image: ghcr.io/llvm/libcxx-android-builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: android-buildkite-builder
      args:
        BASE_IMAGE: docker.io/library/ubuntu:noble
        ANDROID_CLANG_VERSION: r563880
        ANDROID_CLANG_PREBUILTS_COMMIT: 6ae4184bb8706f9731569b9a0a82be3fcdcb951c
        ANDROID_SYSROOT_COMMIT: f8b85cc5262c6e5cbc9a92c1bab2b18b32a4c63f
        <<: [*image_versions, *compiler_versions]
