[package]
name = "tpm2_compat_common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Common types and utilities for TPM2 compatibility layer"

[dependencies]
thiserror.workspace = true
log.workspace = true
cfg-if.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true
bitflags.workspace = true
serde = { workspace = true, optional = true }
zeroize.workspace = true
rand = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["rand"]
no-std = []
serde-support = ["serde"]