name: Build Portable Linux PyTorch Wheels

on:
  workflow_call:
    inputs:
      amdgpu_family:
        required: true
        type: string
      python_version:
        required: true
        type: string
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        required: true
        type: string
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        required: true
        type: string
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        required: true
        type: string
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        required: true
        type: string
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        required: true
        type: string
      rocm_version:
        description: ROCm version to pip install (e.g. "7.10.0a20251124")
        type: string
      pytorch_git_ref:
        description: PyTorch ref to checkout. (typically "nightly", or "release/X.Y")
        required: true
        type: string
      pytorch_patchset:
        description: Patch directory name from where to apply existing patches.
        required: true
        type: string
      repository:
        description: "Repository to checkout. Otherwise, defaults to `github.repository`."
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx101X-dgpu
          - gfx103X-dgpu
          - gfx110X-all
          - gfx1150
          - gfx1151
          - gfx120X-all
          - gfx90X-dcgpu
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx94X-dcgpu
      python_version:
        required: true
        type: string
        default: "3.12"
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        type: string
        default: "v2-staging"
      cloudfront_url:
        description: CloudFront base URL pointing to Python index
        type: string
        default: "https://rocm.devreleases.amd.com/v2"
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        type: string
        default: "https://rocm.devreleases.amd.com/v2-staging"
      rocm_version:
        description: ROCm version to pip install (e.g. "7.10.0a20251124")
        type: string
      pytorch_git_ref:
        description: PyTorch ref to checkout. (typically "nightly", or "release/X.Y")
        required: true
        type: string
        default: "release/2.7"
      pytorch_patchset:
        description: Patch directory name from where to apply existing patches.
        required: true
        type: string
        default: "rocm_2.7"

permissions:
  id-token: write
  contents: read

run-name: Build portable Linux PyTorch Wheels (${{ inputs.amdgpu_family }}, ${{ inputs.python_version }}, ${{ inputs.release_type }})

jobs:
  build_pytorch_wheels:
    name: Build | ${{ inputs.amdgpu_family }} | py ${{ inputs.python_version }} | torch ${{ inputs.pytorch_git_ref }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:583d473f263a289222c48d4b493e2956b2354a45796f09dee6f2c8ecd4504ab6
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
      S3_BUCKET_PY: "therock-${{ inputs.release_type }}-python"
      optional_build_prod_arguments: ""
    outputs:
      cp_version: ${{ env.cp_version }}
      # The following are python package versions produced by the build. The
      # exact versions will depend on workflow inputs and the underlying code.
      # For example:
      #   Inputs
      #     rocm_version       : 7.10.0a20251120
      #     pytorch_git_ref    : release/2.9
      #   Outputs
      #     torch_version      : 2.9.1+rocm7.10.0a20251120
      #     torchaudio_version : 2.9.0+rocm7.10.0a20251120
      #     torchvision_version: 0.24.0+rocm7.10.0a20251120
      #     triton_version     : 3.5.1+rocm7.10.0a20251120
      # Future jobs can use these version outputs to identify newly built
      # packages, for example via `pip install torch==${TORCH_VERSION}`.
      torch_version: ${{ steps.build-pytorch-wheels.outputs.torch_version }}
      torchaudio_version: ${{ steps.build-pytorch-wheels.outputs.torchaudio_version }}
      torchvision_version: ${{ steps.build-pytorch-wheels.outputs.torchvision_version }}
      triton_version: ${{ steps.build-pytorch-wheels.outputs.triton_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: Configure Git Identity
        run: |
          git config --global user.name "therockbot"
          git config --global user.email "therockbot@amd.com"

      - name: Select Python version
        run: |
          python build_tools/github_actions/python_to_cp_version.py \
            --python-version ${{ inputs.python_version }}

      - name: Add selected Python version to PATH
        run: |
          python_dir="/opt/python/${{ env.cp_version }}"
          if ! [ -x "${python_dir}/bin/python" ]; then
            echo "ERROR: Could not find python: ${python_dir}"
            exit 1
          fi
          echo "${python_dir}/bin" >> "$GITHUB_PATH"

      # Checkout nightly sources from https://github.com/pytorch/pytorch
      - name: Checkout PyTorch Source Repos from nightly branch
        if: ${{ inputs.pytorch_git_ref == 'nightly' }}
        run: |
          ./external-builds/pytorch/pytorch_torch_repo.py checkout --repo-hashtag nightly
          ./external-builds/pytorch/pytorch_audio_repo.py checkout --repo-hashtag nightly
          ./external-builds/pytorch/pytorch_vision_repo.py checkout --repo-hashtag nightly
          ./external-builds/pytorch/pytorch_triton_repo.py checkout --patch --patchset nightly

      # Checkout stable sources from https://github.com/ROCm/pytorch
      - name: Checkout PyTorch Source Repos from stable branch
        if: ${{ inputs.pytorch_git_ref != 'nightly' }}
        run: |
          ./external-builds/pytorch/pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag ${{ inputs.pytorch_git_ref }} --patchset ${{ inputs.pytorch_patchset }}
          ./external-builds/pytorch/pytorch_audio_repo.py checkout --require-related-commit
          ./external-builds/pytorch/pytorch_vision_repo.py checkout --require-related-commit
          ./external-builds/pytorch/pytorch_triton_repo.py checkout

      - name: Create pip cache directory
        run: mkdir -p /tmp/pipcache

      - name: Determine optional arguments passed to `build_prod_wheels.py`
        if: ${{ inputs.rocm_version }}
        run: |
          pip install packaging
          python build_tools/github_actions/determine_version.py \
            --rocm-version ${{ inputs.rocm_version }}

      - name: Build PyTorch Wheels
        id: build-pytorch-wheels
        run: |
          echo "Building PyTorch wheels for ${{ inputs.amdgpu_family }}"
          ./external-builds/pytorch/build_prod_wheels.py \
            build \
            --install-rocm \
            --pip-cache-dir /tmp/pipcache \
            --index-url "${{ inputs.cloudfront_url }}/${{ inputs.amdgpu_family }}/" \
            --clean \
            --output-dir ${{ env.PACKAGE_DIST_DIR }} ${{ env.optional_build_prod_arguments }}
          python ./build_tools/github_actions/write_torch_versions.py --dist-dir ${{ env.PACKAGE_DIST_DIR }}

      - name: Sanity Check Wheel
        run: |
          python external-builds/pytorch/sanity_check_wheel.py ${{ env.PACKAGE_DIST_DIR }}/

      - name: Configure AWS Credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-${{ inputs.release_type }}-releases

      - name: Upload wheels to S3 staging
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET_PY }}/${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}/ \
            --recursive --exclude "*" --include "*.whl"

      - name: (Re-)Generate Python package release index for staging
        if: ${{ github.repository_owner == 'ROCm' }}
        env:
          # Environment variables to be set for `manage.py`
          CUSTOM_PREFIX: "${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}"
        run: |
          pip install boto3 packaging
          python ./build_tools/third_party/s3_management/manage.py ${{ env.CUSTOM_PREFIX }}

  generate_target_to_run:
    name: Generate target_to_run
    runs-on: ubuntu-24.04
    outputs:
      test_runs_on: ${{ steps.configure.outputs.test-runs-on }}
      bypass_tests_for_releases: ${{ steps.configure.outputs.bypass_tests_for_releases }}
    steps:
      - name: Checking out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: Generating target to run
        id: configure
        env:
          TARGET: ${{ inputs.amdgpu_family }}
          PLATFORM: "linux"
          # Variable comes from ROCm organization variable 'ROCM_THEROCK_TEST_RUNNERS'
          ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
          LOAD_TEST_RUNNERS_FROM_VAR: false
        run: python ./build_tools/github_actions/configure_target_run.py

  test_pytorch_wheels:
    name: Test | ${{ inputs.amdgpu_family }} | ${{ needs.generate_target_to_run.outputs.test_runs_on }}
    if: ${{ needs.generate_target_to_run.outputs.test_runs_on != '' }}
    needs: [build_pytorch_wheels, generate_target_to_run]
    uses: ./.github/workflows/test_pytorch_wheels.yml
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      test_runs_on: ${{ needs.generate_target_to_run.outputs.test_runs_on }}
      package_index_url: ${{ inputs.cloudfront_staging_url }}
      python_version: ${{ inputs.python_version }}
      torch_version: ${{ needs.build_pytorch_wheels.outputs.torch_version }}
      pytorch_git_ref: ${{ inputs.pytorch_git_ref }}
      repository: ${{ inputs.repository || github.repository }}
      ref: ${{ inputs.ref || '' }}

  upload_pytorch_wheels:
    name: Release PyTorch Wheels to S3
    needs: [build_pytorch_wheels, generate_target_to_run, test_pytorch_wheels]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    env:
      S3_BUCKET_PY: "therock-${{ inputs.release_type }}-python"
      CP_VERSION: "${{ needs.build_pytorch_wheels.outputs.cp_version }}"
      TORCH_VERSION: "${{ needs.build_pytorch_wheels.outputs.torch_version }}"
      TORCHAUDIO_VERSION: "${{ needs.build_pytorch_wheels.outputs.torchaudio_version }}"
      TORCHVISION_VERSION: "${{ needs.build_pytorch_wheels.outputs.torchvision_version }}"
      TRITON_VERSION: "${{ needs.build_pytorch_wheels.outputs.triton_version }}"

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: Configure AWS Credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-${{ inputs.release_type }}-releases

      - name: Determine upload flag
        env:
          BUILD_RESULT: ${{ needs.build_pytorch_wheels.result }}
          TEST_RESULT: ${{ needs.test_pytorch_wheels.result }}
          TEST_RUNS_ON: ${{ needs.generate_target_to_run.outputs.test_runs_on }}
          BYPASS_TESTS_FOR_RELEASES: ${{ needs.generate_target_to_run.outputs.bypass_tests_for_releases }}
        run: python ./build_tools/github_actions/promote_wheels_based_on_policy.py

      - name: Copy PyTorch wheels from staging to release S3
        if: ${{ env.upload == 'true' }}
        run: |
          echo "Copying exact tested wheels to release S3 bucket..."
          aws s3 cp \
            s3://${S3_BUCKET_PY}/${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}/ \
            s3://${S3_BUCKET_PY}/${{ inputs.s3_subdir }}/${{ inputs.amdgpu_family }}/ \
            --recursive \
            --exclude "*" \
            --include "torch-${TORCH_VERSION}-${CP_VERSION}-linux_x86_64.whl" \
            --include "torchaudio-${TORCHAUDIO_VERSION}-${CP_VERSION}-linux_x86_64.whl" \
            --include "torchvision-${TORCHVISION_VERSION}-${CP_VERSION}-linux_x86_64.whl" \
            --include "triton-${TRITON_VERSION}-${CP_VERSION}-linux_x86_64.whl"

      - name: (Re-)Generate Python package release index
        if: ${{ env.upload == 'true' }}
        env:
          # Environment variables to be set for `manage.py`
          CUSTOM_PREFIX: "${{ inputs.s3_subdir }}/${{ inputs.amdgpu_family }}"
        run: |
          pip install boto3 packaging
          python ./build_tools/third_party/s3_management/manage.py ${{ env.CUSTOM_PREFIX }}
