name: Check CI Scripts

permissions:
  contents: read

on:
  push:
    branches:
     - main
    paths:
     - '.ci/**'
     - '.github/workflows/check-ci.yml'
  pull_request:
    paths:
     - '.ci/**'
     - '.github/workflows/check-ci.yml'

jobs:
  test-python:
    name: "Check Python Tests"
    runs-on: ubuntu-24.04
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: .ci
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.14
          cache: 'pip'
      - name: Install Python Dependencies
        run: |
          pip3 install -r .ci/all_requirements.txt
          pip3 install -r .ci/metrics/requirements.lock.txt
          pip3 install pytest==8.4.1
      - name: Run Tests
        working-directory: .ci
        run: pytest
