name: Clang Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - '.github/workflows/clang-tests.yml'
      - '.github/workflows/llvm-project-tests.yml'
      - '!llvm/**'
  pull_request:
    paths:
      - 'clang/**'
      - '.github/workflows/clang-tests.yml'
      - '.github/workflows/llvm-project-tests.yml'
      - '!llvm/**'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  check_clang:
    name: Test clang,lldb,libclc
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: check-clang
      projects: clang;lldb;libclc
