name: Commit Access Greeter

on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  commit-access-greeter:
    permissions:
      issues: write
      pull-requests: read
    if: >-
      github.repository_owner == 'llvm' &&
      github.event.label.name == 'infra:commit-access-request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: llvm/utils/git/

      - name: Setup Automation Script
        working-directory: ./llvm/utils/git/
        run: |
          pip install --require-hashes -r requirements.txt

      - name: Add comments to issue
        working-directory: ./llvm/utils/git/
        env:
          LABEL_NAME: ${{ github.event.label.name }}
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python3 ./github-automation.py \
            --token $GITHUB_TOKEN \
             commit-request-greeter \
             --issue-number $ISSUE_NUMBER
