name: libclc Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'
      - '.github/workflows/llvm-project-tests.yml'
      - '!clang/**'
      - '!llvm/**'
  pull_request:
    paths:
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'
      - '.github/workflows/llvm-project-tests.yml'
      - '!clang/**'
      - '!llvm/**'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  check_libclc:
    name: Test libclc
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: ''
      projects: clang;libclc
