name: LLVM Bugs notifier

permissions:
  contents: read
  issues: read

on:
  issues:
    types:
      - opened

jobs:
  auto-subscribe:
    runs-on: ubuntu-24.04
    if: github.repository == 'llvm/llvm-project'
    steps:
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          check-latest: true
      - run: npm install mailgun.js form-data
      - name: Send notification
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          MAILGUN_API_KEY: ${{ secrets.LLVM_BUGS_KEY }}
        with:
          script: |
            const Mailgun = require('mailgun.js');
            const formData = require('form-data');

            const mailgun = new Mailgun(formData);
            const DOMAIN = 'email.llvm.org';

            const mg = mailgun.client({ username: 'api', key: process.env.MAILGUN_API_KEY });

            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            .then((issue) => {
              var maybeTruncatedBody = issue.data.body;
              if (maybeTruncatedBody.length > 15000) {
                maybeTruncatedBody = maybeTruncatedBody.substring(0,
                    15000) +
                  "<truncated>Please see the issue for the entire body."
              }
              const payload = {
                author : issue.data.user.login,
                issue  : issue.data.number,
                title  : issue.data.title,
                url    : issue.data.html_url,
                labels : issue.data.labels.map((label) => label.name),
                assignee : issue.data.assignees.map((assignee) => assignee.login),
                body   : maybeTruncatedBody
              };

              const data = {
                from: 'LLVM Bugs <llvm-bugs@email.llvm.org>',
                to: 'llvm-bugs@lists.llvm.org',
                subject: `[Bug ${issue.data.number}] ${issue.data.title}`,
                template: 'new-github-issue',
                'o:tracking-clicks': 'no',
                'h:X-Mailgun-Variables': JSON.stringify(payload)
              };

              return mg.messages.create(DOMAIN, data);
            })
            .then((msg) => console.log(msg));
