name: Labeling new issues
on:
  issues:
    types: ['opened']

permissions:
  contents: read

jobs:
  automate-issues-labels:
    permissions:
      issues: write
    runs-on: ubuntu-24.04
    if: github.repository == 'llvm/llvm-project'
    steps:
      - uses: llvm/actions/issue-labeler@5dd955034a6742a2e21d82bf165fcb1050ae7b49 # main
        with:
          repo-token: ${{ secrets.ISSUE_SUBSCRIBER_TOKEN }}
          configuration-path: .github/new-issues-labeler.yml
          include-title: 1
          include-body: 0
          sync-labels: 0
          enable-versioned-regex: 0
