name: 'Repo Lockdown'
on:
  pull_request_target:
    types: opened
    paths-ignore:
      - 'libcxx/**'
      - 'libcxxabi/**'
      - 'libunwind/**'
      - 'runtimes/**'
      - 'lldb/**'
      - '.github/**'
      - 'clang/lib/Format/**'
      - 'clang/include/clang/Format/**'
      - 'clang/docs/**'
      - 'clang/unitests/Format/**'
      - 'clang/tools/clang-format/**'
      - 'llvm/utils/git/**'
      - '*/foo'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          process-only: 'prs'
          pr-comment: >
            This repository does not accept pull requests.
            Please follow http://llvm.org/docs/Contributing.html#how-to-submit-a-patch for contribution to LLVM.
