name: USI CLI Scanner - Search on PR

on:
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  pr_usi_scan:
    name: PR USI scan
    uses: AMD-GH-Actions/usi-scanner/.github/workflows/usi-scan-pr-diffs.yml@v1
    secrets: inherit
    permissions:
      contents: read
    with:
      ScanMode: NewCommitsOnlyDiffs
      ExclusionsRepo: ""
      InclusionsRepo: ""
